pip install --no-index torchvision==0.14.1
pip install --no-index packaging
pip install --no-index sentencepiece
pip install --no-index peft==0.4.0
pip install --no-index einops==0.4.1
pip install --no-index fastapi==0.100.1
pip install --no-index gradio==3.39.0
pip install --no-index markdown2==2.4.10
pip install --no-index numpy==1.24.2
pip install --no-index openai==0.27.8
pip install --no-index opencv_python==4.8.0.74
pip install --no-index Pillow==9.4.0
pip install --no-index pycocotools==2.0.6
pip install --no-index Requests==2.31.0
pip install --no-index shortuuid==1.0.11
pip install --no-index tqdm==4.64.1
pip install --no-index transformers==4.31.0
pip install --no-index uvicorn==0.23.2
pip install --no-index bitsandbytes==0.41.1
pip install --no-index scipy==1.11.2