p install torch==1.13.1
pip install torchvision==0.14.1
pip install packaging
pip install sentencepiece
pip install peft
pip install einops
pip install fastapi
pip install gradio
pip install markdown2
pip install numpy==1.24.2
pip install openai
pip install opencv_python
pip install Pillow==9.4.0
pip install pycocotools==2.0.6
pip install Requests==2.31.0
pip install shortuuid
pip install tqdm==4.64.1
pip install transformers==4.31.0
pip install uvicorn==0.23.2
pip install bitsandbytes==0.41.1
pip install scipy
pip install deepspeed
pip install tensorboard
pip install scikit-image
